<?php

namespace App;

use App\scopes\SellerScope;
use App\Transformers\SellerTransformer;
use Illuminate\Database\Eloquent\Model;

class Seller extends User
{

    public $transformer = SellerTransformer::class;
    public function products(){
        return $this->hasMany(Product::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new SellerScope());
    }
}
